name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes
  workflow_dispatch:        # allows you to run it manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render API
       # run: |
        #  curl -s -o /dev/null -w "%{http_code}" https://tamil-pronunciation-api.onrender.com/health
